network/urls.py
from django.urls import path, re_path

from . import views
from .api_views import api

app_name = "network"


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("api/", api.urls),  # type: ignore
    # Match every url, except if starts with "media" or "static"
    re_path(r"^(?!media|static)", views.index, name="react_root"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
    path("", include("network.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # type: ignore

network/models.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.db.models import Case, Count, Exists, OuterRef, Prefetch, QuerySet, Value, When
from django.forms import ValidationError

from .utility import FileValidator, upload_path

file_validator = FileValidator(max_size=2.5, content_types=("image/jpeg", "image/png"))

if TYPE_CHECKING:
    from django.db.models.manager import RelatedManager

# region Managers


class CustomUserManager(UserManager):
    def fetch_profile(self, request_user: User, username: str):
        # select_related() only works with foreign key and one-to-one
        # fields
        is_owner = Case(When(user__id=request_user.id, then=True), default=False)
        is_following = Exists(request_user.following.filter(id=OuterRef("user__id")))
        liked_by_user = Exists(request_user.liked_posts.filter(id=OuterRef("id")))

        return self.prefetch_related(
            Prefetch(
                "posts",
                queryset=Post.objects.select_related()
                .prefetch_related(
                    Prefetch(
                        "comments",
                        queryset=Comment.objects.select_related().filter(reply=False),
                    ),  # filter related "comments" inside the post QuerySet
                )
                .order_by("-publication_date")
                .annotate(is_following=is_following)
                .annotate(is_owner=is_owner)
                .annotate(likes=Count("liked_by"))  # Doesn't work on 4.1
                .annotate(liked_by_user=liked_by_user),
            )
        ).get(username=username)


class PostManager(models.Manager):
    def request_data(self, request_user):
        liked_by_user = Value(False)
        is_following = Value(False)
        is_owner = Case(When(user__id=request_user.id, then=True), default=False)

        if request_user.is_authenticated:
            # Check if the user has liked the post in each row of the query
            liked_by_user = Exists(request_user.liked_posts.filter(id=OuterRef("id")))
            is_following = Exists(request_user.following.filter(id=OuterRef("user__id")))

        return is_owner, liked_by_user, is_following

    def fetch_all_posts(self, request_user) -> QuerySet[Post]:
        is_owner, liked_by_user, is_following = self.request_data(request_user)

        return (
            self.select_related()
            .prefetch_related(
                Prefetch(
                    "comments",
                    queryset=Comment.objects.select_related().filter(reply=False),
                ),  # filter related "comments" inside the post QuerySet
            )
            .order_by("-publication_date")
            .annotate(is_following=is_following)
            .annotate(is_owner=is_owner)
            .annotate(likes=Count("liked_by"))  # Doesn't work on 4.1
            .annotate(liked_by_user=liked_by_user)
        )

    def fetch_following_posts(self, request_user: User) -> QuerySet[Post]:
        return self.fetch_all_posts(request_user).filter(user__in=request_user.following.all())


# endregion


# region Models


class User(AbstractUser):
    id: int
    posts: RelatedManager[Post]
    liked_posts: RelatedManager[Post]
    comments: RelatedManager[Comment]

    about = models.CharField(blank=True, max_length=255)
    photo = models.ImageField(
        blank=True,
        null=True,
        upload_to=upload_path,
        validators=[file_validator],
    )

    following = models.ManyToManyField("self", related_name="followers", symmetrical=False)

    objects: CustomUserManager = CustomUserManager()

    # Related fields
    # posts = ManyToOne("Post", related_name="user")
    # liked_posts = ManyToMany("Post", related_name="liked_by")
    # comments = ManyToOne("Comment", related_name="user")

    def save(self, *args, **kwargs):
        """
        full_clean is not called automatically on save by Django
        """
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.username}"  # type: ignore


class Post(models.Model):
    id: int
    comments: RelatedManager[Comment]

    user_id: int
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts"
    )
    text = models.CharField(max_length=200)
    publication_date = models.DateTimeField(auto_now_add=True)
    edited = models.BooleanField(default=False)
    last_modified = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="liked_posts", blank=True
    )

    # Related Fields
    # comments = ManyToOne("Comment", related_name="post")

    objects: PostManager = PostManager()

    class Meta:
        ordering = ["-publication_date"]

    def __str__(self):
        return f"{self.text}"


class Comment(models.Model):
    id: int
    replies: RelatedManager[Comment]

    post_id: int
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user_id: int
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    text = models.CharField(max_length=200)
    publication_date = models.DateTimeField(auto_now_add=True)
    reply = models.BooleanField(default=False)
    parent_comment_id: int
    parent_comment = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="replies"
    )

    class Meta:
        ordering = ["-publication_date"]

    def save(self, *args, **kwargs):
        self.full_clean()
        if self.parent_comment is not None:
            if self.parent_comment.post.id != self.post.id:
                raise ValidationError("Parent comment must be from the same post.")
            self.reply = True
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.text} - reply: {self.reply}"  # type: ignore


# endregion

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.forms import ValidationError
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from .models import User


@require_GET
def index(request: HttpRequest):
    context = {
        "user_info": {
            "auth": request.user.is_authenticated,
            "username": request.user.username,  # type: ignore
        }
    }
    return render(request, "network/index.html", context)


@require_http_methods(["GET", "POST"])
def login_view(request: HttpRequest):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect("network:index")
        else:
            return render(
                request,
                "network/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "network/login.html", {"page": "login"})


@require_POST
def logout_view(request: HttpRequest):
    logout(request)
    return redirect("network:index")


@require_http_methods(["GET", "POST"])
def register(request: HttpRequest):
    if request.method == "POST":
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request,
                "network/register.html",
                {"message": "Passwords must match.", "page": "register"},
            )

        # Attempt to create new user
        try:
            username = request.POST["username"]
            email = request.POST["email"]
            user = User.objects.create_user(username=username, email=email, password=password)  # type: ignore
        except ValidationError as e:
            messages = " ".join(
                [f"{key}: {', '.join(value)}" for key, value in e.message_dict.items()]
            )
            return render(
                request,
                "network/register.html",
                {"message": messages, "page": "register"},
            )

        login(request, user)
        return redirect("network:index")
    else:
        return render(request, "network/register.html", {"page": "register"})

network/templates/network/index.html
{% extends "network/layout.html" %}

{% load static %}

{% block scripts %}
  {{ user_info|json_script:"userInfo" }}
  <script type="module" src="{% static 'network/index.js' %}"></script>
  <script type="module" src="{% static 'network/navLinks.js' %}"></script>
{% endblock scripts %}

{% block body %}
  <div id="root"></div>
{% endblock body %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;500&family=Inter&family=Rubik:wght@400;500&display=swap"
          rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'network/index.css' %}" />

    <title>
      {% block title %}
        Social Network
      {% endblock title %}
    </title>
    {% block scripts %}
    {% endblock scripts %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-navbar nav-pills sticky-top">
      <div class="container-fluid justify-content-center">
        <a class="navbar-brand" href="/">Social Network</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-link" href="/profile/{{ user.username }}"><strong>{{ user.username }}</strong></a>
            {% endif %}

            <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
            {% if user.is_authenticated %}
              <a class="nav-link" href="/following">Following</a>
              <form action="{% url 'network:logout' %}" method="post">
                {% csrf_token %}
                <a class="nav-link" href="logout" onclick="this.parentNode.submit();">Log Out</a>
              </form>
            {% else %}

              {% url 'network:login' as login_url %}
              {% if request.path == login_url %}
                <a class="nav-link active" href="{% url 'network:login' %}">Log In</a>
              {% else %}
                <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
              {% endif %}

              {% url 'network:register' as register_url %}
              {% if request.path == register_url %}
                <a class="nav-link active" href="{% url 'network:register' %}">Register</a>
              {% else %}
                <a class="nav-link" href="{% url 'network:register' %}">Register</a>
              {% endif %}

            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="body">
      {% block body %}
      {% endblock body %}
    </div>
  </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

  <div class="container mt-3 px-4 center-form">
    <h2 class="mb-3">Login</h2>
    <div class="card">
      {% if message %}<div>{{ message }}</div>{% endif %}

      <div class="card-body">
        <form action="{% url 'network:login' %}" method="post" class="mb-3">
          {% csrf_token %}
          <div class="form-group mb-3">
            <input autofocus
                   class="form-control form-input"
                   type="text"
                   name="username"
                   placeholder="Username"/>
          </div>
          <div class="form-group mb-3">
            <input class="form-control form-input"
                   type="password"
                   name="password"
                   placeholder="Password"/>
          </div>
          <input class="btn btn-primary px-3" type="submit" value="Login" />
        </form>
        Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>
      </div>
    </div>
  </div>

{% endblock body %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}
  <div class="container mt-3 px-4 center-form">
    <h2>Register</h2>
    <div class="card">
      <div class="card-body">

        {% if message %}<div>{{ message }}</div>{% endif %}

        <form action="{% url 'network:register' %}" method="post" class="mb-3">
          {% csrf_token %}
          <div class="form-group mb-3">
            <input class="form-control form-input"
                   autofocus
                   type="text"
                   name="username"
                   placeholder="Username"/>
          </div>
          <div class="form-group mb-3">
            <input class="form-control form-input"
                   type="email"
                   name="email"
                   placeholder="Email Address"/>
          </div>
          <div class="form-group mb-3">
            <input class="form-control form-input"
                   type="password"
                   name="password"
                   placeholder="Password"/>
          </div>
          <div class="form-group mb-3">
            <input class="form-control form-input"
                   type="password"
                   name="confirmation"
                   placeholder="Confirm Password"/>
          </div>

          <input class="btn btn-primary" type="submit" value="Register"/>
        </form>
        Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
      </div>
    </div>
  </div>
{% endblock body %}